# Generated by Django 5.0 on 2024-01-15 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_admin', models.CharField(max_length=30)),
                ('prenom_admin', models.CharField(max_length=25)),
                ('email_admin', models.EmailField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cne', models.CharField(max_length=11)),
                ('nom_etudiant', models.CharField(max_length=50)),
                ('prenom_etudiant', models.CharField(max_length=50)),
                ('email_etudiant', models.CharField(default=' ', max_length=50)),
                ('adresse', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=12)),
                ('niveau', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cne', models.CharField(max_length=10)),
                ('nom', models.CharField(max_length=30)),
                ('prenom', models.CharField(max_length=20)),
                ('add', models.FloatField(default=0.0, null=True)),
                ('sir', models.FloatField(default=0.0, null=True)),
                ('programmation', models.FloatField(default=0.0, null=True)),
                ('tec', models.FloatField(default=0.0, null=True)),
                ('an', models.FloatField(default=0.0, null=True)),
                ('tst', models.FloatField(default=0.0, null=True)),
                ('moyenne', models.FloatField(default=0.0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PremiereA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cne', models.CharField(max_length=11)),
                ('nom_etudiant', models.CharField(max_length=50)),
                ('prenom_etudiant', models.CharField(max_length=50)),
                ('email_etudiant', models.CharField(default=' ', max_length=50)),
                ('adresse', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=12)),
                ('niveau', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Professeur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(max_length=15)),
                ('nom_professeur', models.CharField(max_length=20)),
                ('prenom_professeur', models.CharField(max_length=20)),
                ('departement', models.CharField(max_length=20)),
                ('mot_de_passe', models.CharField(default=' ', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
    ]
