# Generated by Django 5.0 on 2024-01-15 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
