# Generated by Django 5.0 on 2024-01-15 22:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_delete_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='notes',
            name='prenom',
        ),
    ]
